### ISSUE TITLE
The gopkg.in import path is incorretct

### ISSUE THREAD

**Issue by rgruchalski-klarrio** [tchap/go-patricia#34]
The readme says: to import the "gopkg.in/tchap/go-patricia.v2/patricia" but the go.mod declares the package as "github.com/tchap/go-patricia/v2". When using this module as a dependency and doing go mod tidy, I get this error:

```
go: github.com/monzo/calico-accountant/watch imports
	github.com/projectcalico/libcalico-go/lib/client imports
	github.com/projectcalico/libcalico-go/lib/backend imports
	github.com/projectcalico/libcalico-go/lib/backend/etcd imports
	github.com/projectcalico/libcalico-go/lib/hwm imports
	gopkg.in/tchap/go-patricia.v2/patricia: gopkg.in/tchap/go-patricia.v2@v2.3.1: parsing go.mod:
	module declares its path as: github.com/tchap/go-patricia/v2
	        but was required as: gopkg.in/tchap/go-patricia.v2
```

Either remove the go.mod or provide proper instructions to require the v2.x.x version.

**Comment by tchap** [comment]
Fixed in 120e0b621dfebd4d4431347ca8659eecb5fec50f

**Comment by AlexeyKukin** [comment]
Hello!
seems problem still here...

I've import "github.com/projectcalico/libcalico-go/lib/client"
and get

`
>go mod tidy
go: finding module for package github.com/projectcalico/libcalico-go/lib/client
go: found github.com/projectcalico/libcalico-go/lib/client in github.com/projectcalico/libcalico-go v1.7.3
go: finding module for package github.com/kelseyhightower/envconfig
go: finding module for package github.com/sirupsen/logrus
go: finding module for package github.com/projectcalico/go-yaml-wrapper
go: finding module for package github.com/satori/go.uuid
go: finding module for package github.com/onsi/ginkgo/extensions/table
go: finding module for package github.com/onsi/ginkgo
go: finding module for package gopkg.in/go-playground/validator.v8
go: finding module for package github.com/onsi/gomega
go: finding module for package github.com/coreos/etcd/client
go: finding module for package github.com/coreos/etcd/pkg/transport
go: finding module for package golang.org/x/net/context
go: finding module for package k8s.io/apimachinery/pkg/apis/meta/v1
go: finding module for package k8s.io/apimachinery/pkg/fields
go: finding module for package k8s.io/apimachinery/pkg/runtime
go: finding module for package k8s.io/apimachinery/pkg/runtime/schema
go: finding module for package k8s.io/apimachinery/pkg/runtime/serializer
go: finding module for package k8s.io/apimachinery/pkg/util/intstr
go: finding module for package k8s.io/apimachinery/pkg/util/wait
go: finding module for package k8s.io/apimachinery/pkg/watch
go: finding module for package k8s.io/client-go/kubernetes
go: finding module for package k8s.io/client-go/pkg/api
go: finding module for package k8s.io/client-go/pkg/api/v1
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth
go: finding module for package k8s.io/client-go/rest
go: finding module for package k8s.io/client-go/tools/cache
go: finding module for package k8s.io/client-go/tools/clientcmd
go: finding module for package gopkg.in/tchap/go-patricia.v2/patricia
go: finding module for package k8s.io/apimachinery/pkg/api/errors
go: found github.com/kelseyhightower/envconfig in github.com/kelseyhightower/envconfig v1.4.0
go: found github.com/projectcalico/go-yaml-wrapper in github.com/projectcalico/go-yaml-wrapper v0.0.0-20191112210931-090425220c54
go: found github.com/satori/go.uuid in github.com/satori/go.uuid v1.2.0
go: found github.com/sirupsen/logrus in github.com/sirupsen/logrus v1.8.1
go: found gopkg.in/go-playground/validator.v8 in gopkg.in/go-playground/validator.v8 v8.18.2
go: found github.com/onsi/ginkgo in github.com/onsi/ginkgo v1.16.4
go: found github.com/onsi/ginkgo/extensions/table in github.com/onsi/ginkgo v1.16.4
go: found github.com/onsi/gomega in github.com/onsi/gomega v1.13.0
go: found github.com/coreos/etcd/client in github.com/coreos/etcd v3.3.25+incompatible
go: found github.com/coreos/etcd/pkg/transport in github.com/coreos/etcd v3.3.25+incompatible
go: found golang.org/x/net/context in golang.org/x/net v0.0.0-20210614182718-04defd469f4e
go: found k8s.io/apimachinery/pkg/apis/meta/v1 in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/fields in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/runtime in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/runtime/schema in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/runtime/serializer in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/util/intstr in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/util/wait in k8s.io/apimachinery v0.21.1
go: found k8s.io/apimachinery/pkg/watch in k8s.io/apimachinery v0.21.1
go: found k8s.io/client-go/kubernetes in k8s.io/client-go v0.21.1
go: found k8s.io/client-go/plugin/pkg/client/auth in k8s.io/client-go v0.21.1
go: found k8s.io/client-go/rest in k8s.io/client-go v0.21.1
go: found k8s.io/client-go/tools/cache in k8s.io/client-go v0.21.1
go: found k8s.io/client-go/tools/clientcmd in k8s.io/client-go v0.21.1
go: found gopkg.in/tchap/go-patricia.v2/patricia in gopkg.in/tchap/go-patricia.v2 v2.3.1
go: found k8s.io/apimachinery/pkg/api/errors in k8s.io/apimachinery v0.21.1
go: calicoget imports
        github.com/projectcalico/libcalico-go/lib/client imports
        github.com/projectcalico/libcalico-go/lib/backend imports
        github.com/projectcalico/libcalico-go/lib/backend/etcd imports
        github.com/projectcalico/libcalico-go/lib/hwm imports
        gopkg.in/tchap/go-patricia.v2/patricia: gopkg.in/tchap/go-patricia.v2@v2.3.1: parsing go.mod:
        module declares its path as: github.com/tchap/go-patricia/v2
                but was required as: gopkg.in/tchap/go-patricia.v2
`

**Comment by tchap** [comment]
@AlexeyKukin I am afraid this cannot be fixed on my side. By defining the canonical module path, the old path stopped working with modules-aware tools. So the import path must be fixed in `libcalico-go`. I probably caused this, didn't know about this behavior. The canonical module path should have included `gopkg.in`, but this cannot be changed any more as that would now break the module name for everybody using the name as defined now.
